name: Build and deploy a container to an Azure Web App

env:
  AZURE_WEBAPP_NAME: savannah

on:
  push:
    branches:
      - main

permissions:
  contents: 'read'
  packages: 'write'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Setup python3.12
      - name: Set up python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

        # Create virtual environment to isolate depedencies
      - name: Create a virtual environment
        run: |
          python3.12 -m venv env
          source env/bin/activate

      # Install dependencies for running tests
      - name: Install dependencies
        run: |
          source env/bin/activate
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt

      # Run pytest to ensure all tests pass
      - name: Run pytest tests
        env:
          DB_NAME: ${{secrets.DB_NAME}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
          DB_PORT: ${{secrets.DB_PORT}}
          DB_USER: ${{secrets.DB_USER}}
          DB_HOST: ${{secrets.DB_HOST}}
          SECRET_KEY: ${{secrets.SECRET_KEY}}
          ALGORITHM: ${{secrets.ALGORITHM}}
        run: |
          source env/bin/activate
          pytest --disable-warnings

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: savannah
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: savannah
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@85270a1854658d167ab239bce43949edb336fa7c
        with:
          app-name: savannah
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'ghcr.io/${{ env.REPO }}:${{ github.sha }}'
